version: "3"

services:
  spark-master:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    ports:
      - 4040:4040
      - 7077:7077
      - 8081:8081
      - 8080:8080
      - 18080:18080
    restart: unless-stopped
    command: ["/spark-master"]

  spark-worker:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    command: ["/spark-worker"]

  app:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    volumes:
      - ./src:/opt/project
    command: sleep infinity