version: "3"

services:
  spark_master:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    ports:
      - 4040:4040
      - 7077:7077
      - 8081:8081
      - 8080:8080
      - 18080:18080
    restart: unless-stopped
    command: sh /master.sh

  spark_worker1:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    container_name: spark_worker1
    environment: 
      - spark_master=spark://spark_master:7077
    command: sh /worker.sh

  spark_worker2:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    container_name: spark_worker2
    environment: 
      - spark_master=spark://spark_master:7077
    command: sh /worker.sh

  app:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    volumes:
      - ./src:/opt/project
    command: sleep infinity